# GitHub 访问选项；主项目与独立测试构建共用。
set(TFL_GITHUB_MIRROR "direct" CACHE STRING "GitHub access: direct or mirror hostname")
set_property(CACHE TFL_GITHUB_MIRROR PROPERTY STRINGS direct ghfast.top gh-proxy.com ghproxy.net)
set(TFL_GITHUB_PREFIX "" CACHE STRING "Custom prefix prepended to GitHub URLs")
set(TFL_GIT_PROXY "" CACHE STRING "HTTP(S) proxy for dependency downloads")
option(TFL_PARTIAL_CLONE "Use --filter=blob:none for Taskflow" ON)
mark_as_advanced(TFL_GITHUB_PREFIX TFL_GIT_PROXY TFL_PARTIAL_CLONE)
if(TFL_GITHUB_PREFIX)
    set(TFL_EFFECTIVE_PREFIX "${TFL_GITHUB_PREFIX}")
elseif(TFL_GITHUB_MIRROR STREQUAL "direct")
    set(TFL_EFFECTIVE_PREFIX "")
else()
    set(TFL_EFFECTIVE_PREFIX "https://${TFL_GITHUB_MIRROR}/")
endif()
if(TFL_UPDATE_DEPS)
    message(DEPRECATION "Dependencies are pinned; select a new ref/commit instead of TFL_UPDATE_DEPS")
endif()

# 每次配置都校验已有文件；新下载先写临时文件，成功后才进入缓存。
function(tfl_download_checked url destination expected_hash)
    if(EXISTS "${destination}")
        file(SHA256 "${destination}" _actual_hash)
        if(NOT _actual_hash STREQUAL expected_hash)
            message(FATAL_ERROR "Dependency checksum mismatch: ${destination}")
        endif()
        return()
    endif()
    if(TFL_GIT_PROXY)
        set(_had_proxy OFF)
        if(DEFINED ENV{https_proxy})
            set(_had_proxy ON)
        endif()
        set(_old_proxy "$ENV{https_proxy}")
        set(ENV{https_proxy} "${TFL_GIT_PROXY}")
    endif()
    file(DOWNLOAD "${url}" "${destination}.download"
        STATUS _status TLS_VERIFY ON TIMEOUT 180 INACTIVITY_TIMEOUT 30)
    if(TFL_GIT_PROXY)
        if(_had_proxy)
            set(ENV{https_proxy} "${_old_proxy}")
        else()
            unset(ENV{https_proxy})
        endif()
    endif()
    list(GET _status 0 _code)
    if(NOT _code EQUAL 0)
        list(GET _status 1 _error)
        message(FATAL_ERROR "Dependency download failed: ${_error}. Set a local dependency path or mirror.")
    endif()
    file(SHA256 "${destination}.download" _actual_hash)
    if(NOT _actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "Downloaded dependency checksum mismatch: ${destination}.download")
    endif()
    file(RENAME "${destination}.download" "${destination}")
endfunction()

# 只检出 taskflow/ 和许可证；保留 .git 以核对提交和缓存完整性。
function(tfl_fetch_taskflow destination commit)
    find_package(Git REQUIRED)
    set(_git_args -c http.lowSpeedLimit=1000 -c http.lowSpeedTime=30)
    if(TFL_GIT_PROXY)
        list(APPEND _git_args -c "http.proxy=${TFL_GIT_PROXY}")
    endif()
    if(NOT EXISTS "${destination}/.git")
        file(MAKE_DIRECTORY "${destination}")
        execute_process(COMMAND "${GIT_EXECUTABLE}" init "${destination}"
            RESULT_VARIABLE _rc OUTPUT_QUIET ERROR_QUIET)
        if(NOT _rc EQUAL 0)
            message(FATAL_ERROR "Cannot initialize Taskflow cache: ${destination}")
        endif()
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${destination}" rev-parse --verify HEAD
        RESULT_VARIABLE _head_rc OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(_head_rc EQUAL 0)
        if(NOT _head STREQUAL commit)
            message(FATAL_ERROR "Unexpected commit in Taskflow cache: ${destination}")
        endif()
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${destination}" status --porcelain
            RESULT_VARIABLE _rc OUTPUT_VARIABLE _dirty OUTPUT_STRIP_TRAILING_WHITESPACE)
        if(NOT _rc EQUAL 0 OR _dirty)
            message(FATAL_ERROR "Modified/incomplete Taskflow cache: ${destination}; use TASKFLOW_LOCAL_PATH for a custom checkout")
        endif()
    else()
        set(_filter "")
        if(TFL_PARTIAL_CLONE)
            set(_filter --filter=blob:none)
        endif()
        set(_url "${TFL_EFFECTIVE_PREFIX}https://github.com/taskflow/taskflow.git")
        # 使用 origin 保存 URL，partial clone 后续按需取对象仍可复用镜像。
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${destination}" config remote.origin.url "${_url}"
            RESULT_VARIABLE _rc)
        if(NOT _rc EQUAL 0)
            message(FATAL_ERROR "Cannot configure Taskflow remote")
        endif()
        execute_process(
            COMMAND "${GIT_EXECUTABLE}" ${_git_args} -C "${destination}"
                fetch --depth 1 ${_filter} origin "${commit}"
            TIMEOUT 240 RESULT_VARIABLE _rc)
        if(NOT _rc EQUAL 0)
            message(FATAL_ERROR "Taskflow fetch failed; use TASKFLOW_LOCAL_PATH or retry with TFL_PARTIAL_CLONE=OFF")
        endif()
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${destination}"
            sparse-checkout set --no-cone /taskflow/ /LICENSE
            RESULT_VARIABLE _rc)
        if(NOT _rc EQUAL 0)
            message(FATAL_ERROR "Taskflow sparse-checkout failed")
        endif()
        execute_process(COMMAND "${GIT_EXECUTABLE}" ${_git_args} -C "${destination}"
            checkout --detach "${commit}" TIMEOUT 240 RESULT_VARIABLE _rc)
        if(NOT _rc EQUAL 0)
            message(FATAL_ERROR "Taskflow checkout failed")
        endif()
    endif()
    if(NOT EXISTS "${destination}/taskflow/taskflow.hpp")
        message(FATAL_ERROR "Taskflow cache is missing taskflow/taskflow.hpp: ${destination}")
    endif()
    message(STATUS "[taskflow] commit: ${commit}")
endfunction()
